USE master
GO

CREATE DATABASE DENEME
GO
USE DENEME
GO	
CREATE TABLE SERTIFIKALAR(
ID INT PRIMARY KEY IDENTITY,
KategoriAdi NVARCHAR(30) unique NOT NULL,
Aciklama NVARCHAR(max),
EklenmeTarihi SMALLDATETIME DEFAULT GETDATE()
)
GO 
CREATE TABLE KEDILER(
ID INT PRIMARY KEY IDENTITY,
UrunAdi NVARCHAR(75) UNIQUE NOT NULL,
Fiyat DECIMAL(7,2) DEFAULT 0 CHECK (Fiyat>=0),
Stok INT DEFAULT 0 CHECK (Stok>=0),
KategoriID INT  NULL REFERENCES SERTIFIKALAR(ID),
EklenmeTarihi SMALLDATETIME DEFAULT GETDATE(),
AktifMi BIT DEFAULT 1
)
USE DENEME
INSERT INTO SERTIFIKALAR (KategoriAdi,Aciklama) VALUES ('Meyve','Meyveler')
INSERT INTO SERTIFIKALAR (KategoriAdi,Aciklama) VALUES ('Sebze','Sebzeler')

ALTER TABLE SERTIFIKALAR
ALTER COLUMN EklenmeTarihi smalldatetime NOT NULL 

ALTER TABLE SERTIFIKALAR
ALTER COLUMN EklenmeTarihi  SMALLDATETIME NOT NULL

DROP DATABASE DENEME
